### PR TITLE
[SwipeRefresh] Add clipIndicatorToPadding parameter

### LINKED ISSUE #377: SwipeRefresh placed over TopAppBar when used inside BottomSheetScaffold
## Describe the bug
`SwipeRefresh` inidicator is displaying over `TopAppBar` when used inside `BottomSheetScaffold`. The problem is not appearing when using `SwipeRefresh` inside `Scaffold`

## To Reproduce
Use `SwipeRefresh` inside `BottomsheetScaffold` with `TopAppBar`

## Expected behavior
Place `SwipeRefresh` indicator under `TopAppBar` like it's done when wrapped `Scaffold`

## Environment:
 - Android OS version: 11
 - Device: Emulator of Pixel 3A, API 30 x86
 - Accompanist version: 0.8.1

### Minimal code to reproduce issue:
```kotlin
@Composable
private fun TopBar() {
  TopAppBar() {
    Text(text = "Reproduction")
  }
}

@Composable
private fun RefreshableContent() {
  LazyColumn(Modifier.fillMaxWidth()) {
    items(100) {
      Text("Content is here")
    }
  }
}

@ExperimentalMaterialApi
@Composable
private fun Broken() {
  BottomSheetScaffold(sheetContent = {  }, topBar = {TopBar()}) {
    SwipeRefresh(
      state = rememberSwipeRefreshState(isRefreshing = false),
      onRefresh = {}) {
      RefreshableContent()
    }
  }
}

@Composable
private fun Correct() {
  Scaffold(Modifier.fillMaxWidth(), topBar = { TopBar() }) {
    SwipeRefresh(
      state = rememberSwipeRefreshState(isRefreshing = false),
      onRefresh = {}) {
      RefreshableContent()
    }
  }
}

class MainFragment : Fragment() {
  companion object {
    fun newInstance() = MainFragment()
  }

  @ExperimentalMaterialApi
  override fun onCreateView(
    inflater: LayoutInflater, container: ViewGroup?,
    savedInstanceState: Bundle?
  ): View {
    return ComposeView(requireContext()).apply {
      setContent {
        // Replace with Correct() to use Scaffold instead of BottomSheetScaffold
        Broken()
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by chrisbanes**
We now clip the indicator to the bounds of the content, or the indicatorPadding, depending on what value is provided.

Fixes #377

### CODE REVIEW

File: swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt [hunk 1]
```diff
@@ -209,6 +210,8 @@ private class SwipeRefreshNestedScrollConnection(
  * @param indicatorPadding Content padding for the indicator, to inset the indicator in if required.
  * @param indicator the indicator that represents the current state. By default this
  * will use a [SwipeRefreshIndicator].
+ * @param clipIndicatorToPadding Whether to clip the indicator to [indicatorPadding]. If false is
+ * provided the indicator will be clipped to the [content] bounds. Defaults to true.
```
Comment (nickbutcher) [inline swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt:214]: will *not* be clipped??

File: swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt [hunk 2]
```diff
@@ -254,10 +258,18 @@ fun SwipeRefresh(
 
         Box(
             Modifier
-                .align(indicatorAlignment)
+                // If we're not clipping to the padding, we use clipToBounds() before the padding()
+                // modifier.
+                .let { if (!clipIndicatorToPadding) it.clipToBounds() else it }
```
Comment (nickbutcher) [inline swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt:263]:
```suggestion
                .then(if (!clipIndicatorToPadding) it.clipToBounds() else this)
```

File: swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt [hunk 3]
```diff
@@ -254,10 +258,18 @@ fun SwipeRefresh(
...
                 .padding(indicatorPadding)
+                .matchParentSize()
+                // Else, if we're are clipping to the padding, we use clipToBounds() after
+                // the padding() modifier.
+                .let { if (clipIndicatorToPadding) it.clipToBounds() else it }
```
Comment (nickbutcher) [inline swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt:268]: Use `then` ?

**Review by nickbutcher — APPROVED** [review]
A doc question and some small suggestions otherwise LGTM.

File: swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt (hunk 1 above)
Comment (chrisbanes) [reply swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt:214]: Nope, the comment is right. `true` == clip to the padding. `false` the wider bounds.
