### PR TITLE
[Pager] Handle infinite constraints

### LINKED ISSUE #300: [Pager] HorizontalPager inside scrollable view incorrectly forms the height
## Describe the bug
HorizontalPager inside scrollable view incorrectly forms the height. But if we set fixed size it's work fine

## To Reproduce
Put Horizontal pager in scrollable container

## Expected behavior
pager automatically resized base on content

## Screenshots?
run code and uncomment key lines

## Additional context
  
```kotlin
val pages = listOf(
        "one",
        "two"
    )
    Column(Modifier.verticalScroll(rememberScrollState()))
    {
        val coroutineScope = rememberCoroutineScope()
        val pagerState = rememberPagerState(pageCount = 2, 1)
        TabRow(
            selectedTabIndex = pagerState.currentPage,
        ) {
            pages.forEachIndexed { index, title ->
                val isSelected = pagerState.currentPage == index
                Tab(
                    text = {
                        Text(
                            text = title,
                        )
                    },
                    selected = isSelected,
                    onClick = {
                        coroutineScope.launch {
                            pagerState.animateScrollToPage(index)
                        }
                    },
                )
            }
        }

        HorizontalPager(
            state = pagerState,
            Modifier
                .background(Color.Blue)
//                .height(1200.dp)  worked
//                .fillMaxHeight() not worker
        ) { index ->
            Column(
                Modifier
                    .fillMaxHeight()
                    .background(Color.Cyan)
            ) {
                repeat(50) {
                    Text(text = "aaaa")
                }
            }
        }
    }

```

### PR DESCRIPTION
**Pull request by chrisbanes**
Current Pager blindly uses the maxHeight/Width constraints, which breaks down when the pager is given infinite max constraints.

This PR updates our measure/layout to wrap the page content by default, and then coerces that by the min constraints.

Fixes #300

### CODE REVIEW

**Review by andkulikov — APPROVED** [review]

File: pager/src/androidTest/java/com/google/accompanist/pager/HorizontalPagerInfiniteHeightTest.kt [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+@RunWith(JUnit4::class)
+class HorizontalPagerInfiniteHeightTest {
+    @get:Rule
+    val rule = createComposeRule()
+
+    @Test
+    fun horizontalPagerInScrollableColumn() {
+        rule.setContent {
+            Column(Modifier.verticalScroll(rememberScrollState())) {
+                HorizontalPager(
```
Comment (nickbutcher) [inline pager/src/androidTest/java/com/google/accompanist/pager/HorizontalPagerInfiniteHeightTest.kt:53]: Shouldn't this be a `VerticalPager` in a `Column` or use a `Row`?
