### PR TITLE
Fix for Pager loosing its restored or initial current page

### LINKED ISSUE #885: [Pager] Current page jumps to 0 in instrumented tests
## Describe the bug
The current page of `HorizontalPager` seems to emit 0 in instrumented tests even when the initial page is not 0 and doesn't change. This doesn't happen when running the app normally.
 
## To Reproduce
With the following test:
```
@RunWith(AndroidJUnit4::class)
class ExampleInstrumentedTest {
    @get:Rule
    val composeRule = createAndroidComposeRule<MainActivity>()

    @Test fun testScratch() {
        // Set the composable content.
        composeRule.setContent {
            ScratchScreen()
        }

        // Execute the test.
        composeRule.onNodeWithText("Item 10")
            .assertExists(composeRule.onRoot().printToString())
            .assertIsDisplayed()
    }
}
```

and the following compose code:
```
@OptIn(ExperimentalPagerApi::class)
@Composable
internal fun ScratchScreen() {
    Scaffold {
        val pagerState = rememberPagerState(initialPage = 10)

        LaunchedEffect(pagerState) {
            snapshotFlow { pagerState.currentPage }.collect {
                Log.d("SCRATCH", "Current page $it")
            }
        }

        HorizontalPager(
            state = pagerState,
            count = 20
        ) { page ->
            Text(
                text = "Item $page",
                modifier = Modifier.background(Color.Red)
                    .padding(8.dp)
                    .fillMaxWidth()
            )
        }
    }
}
```

The output is:
```
2021-11-22 13:46:46.043 14883-14907/com.example.myapplication I/TestRunner: started: testScratch(com.example.myapplication.ExampleInstrumentedTest)
2021-11-22 13:46:46.655 14883-14883/com.example.myapplication D/SCRATCH: Current page 10
2021-11-22 13:46:46.662 14883-14883/com.example.myapplication D/SCRATCH: Current page 0
2021-11-22 13:46:46.850 14883-14883/com.example.myapplication D/SCRATCH: Current page 10
2021-11-22 13:46:46.852 14883-14883/com.example.myapplication D/SCRATCH: Current page 0
2021-11-22 13:46:46.911 14883-14883/com.example.myapplication D/SCRATCH: Current page 10
2021-11-22 13:46:46.913 14883-14883/com.example.myapplication D/SCRATCH: Current page 0
2021-11-22 13:46:47.899 14883-14907/? I/TestRunner: finished: testScratch(com.example.myapplication.ExampleInstrumentedTest)
```

## Expected behavior
"Current page 10" would be the only output and there would be no "Current page 0"

## Environment:
 - Android OS version: Android 11
 - Device: Google Pixel 2
 - Accompanist version: `0.21.3-beta` and `0.20.2`

## Additional context
I had a go at debugging this and it seems like `onScrollFinished` is being called before any visible items are loaded so [this line](https://github.com/google/accompanist/blob/76ab3e954177e7e99ffde0d322cd563287bdb970/pager/src/main/java/com/google/accompanist/pager/PagerState.kt#L283) sets the current page to 0

### LINKED ISSUE #890: Pager currentPage become 0 when use in LazyColumn
## Describe the bug
when i use HorizontalPager in LazyColumn like HorizontalPagerLoopingSample,i set 
`val startIndex = Int.MAX_VALUE / 2`
`val pagerState = rememberPagerState(initialPage = startIndex)`
`Log.d("page","init currentPage:${pagerState.currentPage}")`

when first compose,log is:
init currentPage:1073741823
it's ok

when scroll the pager(in lazy column) out screen and back,log is:
init currentPage:1073741823
init currentPage:0

then if invoke `pagerState.animateScrollToPage(pagerState.currentPage + 1)`, it's wrong。

## Expected behavior
currentPage should be 1073741823

## Environment:
 - Android OS version: Android 11
 - Device: OPPO A11
 - Accompanist version: accompanist-pager:0.21.3-beta

### LINKED ISSUE #893: Using of rememberPagerState while using Google Accompanist HorizantalPager is causing multiple recomposes when screen loads first time
I am using HorizantalPager in my application.

This is the code to simulate the behaviour

```
class QuotesFragment: Fragment(R.layout.compose_list) {
    private lateinit var binding: ComposeListBinding
    
 @ExperimentalPagerApi
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        binding = ComposeListBinding.bind(view)
       
       binding.composeView.setContent {
      }

    }

```

`@Composable
@ExperimentalPagerApi
fun PagerTest() {
    val pagerState = rememberPagerState()
    Log.i(Tag.Temp, "${pagerState.currentPage} ${pagerState.pageCount}")
    HorizontalPager(count = 5, state = pagerState) { page ->
        Text(text = "$page")
    }
}`

Steps to reproduce

1. Move two pages
2. Log shows in last line -> 2 5
3. Go to some other fragment and comeback to fragment which is showing this test pager
4. Log shows 
    2 0
    0 0
    0 5

This causing 

a. compose three times
b. making us loose the state of current page ( while in UI it is still showing 2nd page not 0th page )
c. If we implement some control based on current page value it is giving wrong results. For example next button calls,  pagerState.animateScrollToPage(pagerState.currentPage + 1, 0f),  It should move to page = 3 on clicking it on current state , while it moves back to page = 1 as according pagerState the currentPage is 0

### LINKED ISSUE #895: [PagerState] Not possible to pass a pagerState without the "currentPage" attribute getting overwritten?
## Describe the bug
I introduced a bug in my app where a race condition between count and currentPage attributes of the pager are not in sync causing an IndexOutOfBoundsException.
My naive fix is to just dodge the (temporary) case when the selected page is on an index for a recently removed item.
So I wrote a unit test where I pass a pager state into the composable with a currentPage index that is out of bounds.

But I noticed that when the code executes the "currentPage" attribute is overwritten as it reaches the pager, meaning I cannot write a unit test that checks that my composable can handle the case when currentPage exceeds the index of the list backing my pager.

## To Reproduce
My test executes the following:
```
MyComposable(state = MyState(adapterItems = listOf(
             MyItem()
   )),
   pagerState = PagerState(currentPage = 2)
)
```
My code:
```
@ExperimentalPagerApi
@Composable
internal fun MyComposable(
    state: MutableState<MyItem>,
    @VisibleForTesting pagerState: PagerState = rememberPagerState(0)
) {
    val pages = state.adapterItems()
    check(pages.isNotEmpty())

...
 HorizontalPager(
            state = pagerState,
            count = pages.size
        ) { page ->
            val adapterItem = pages[page]
            // pagerState.currentPage is 0 even if I pass currentPage = 2
            if (pagerState.currentPage >= pages.size) {
                // The test case that I would like to verify
            } else {
            ...
...
```

## Expected behavior
pagerState.currentPage is refreshed

## Screenshots?
N/A

## Environment:
 - Android OS version: Android 11, not important though
 - Device: Samsung Galaxy S21+, not important though
 - Accompanist version: 0.21.3-beta

## Additional context
N/A

### PR DESCRIPTION
**Pull request by andkulikov**
Fixes #890
Fixes #895
Fixes #893
Fixes #885

### CODE REVIEW

File: pager/src/main/java/com/google/accompanist/pager/Pager.kt [hunk 1]
```diff
@@ -248,6 +249,7 @@ internal fun Pager(
         // When a 'scroll' has finished, notify the state
         snapshotFlow { state.isScrollInProgress }
             .filter { !it }
+            .drop(1)
```
Comment (chrisbanes) [inline pager/src/main/java/com/google/accompanist/pager/Pager.kt:252]: Add a comment to why?

**Review by chrisbanes — APPROVED** [review]
LGTM!

**Review by chrisbanes — APPROVED** [review]
