### PR TITLE
[SwipeRefresh] Make scrollable requirements clearer in docs

### LINKED ISSUE #404: SwipeRefresh does not work with a child of type Column()
## Describe the bug
I'm presenting a screen with data on it. This data is presented in a simple Column (*not* LazyColum) I want to allow the user to update the data using a swipe-to-refresh gesture

## To Reproduce
1. Create a screen like with then following content:

        val viewModel: MyViewModel = viewModel()
        val isRefreshing by viewModel.isRefreshing.collectAsState()

        SwipeRefresh(
            state = rememberSwipeRefreshState(isRefreshing),
            onRefresh = { viewModel.refresh() },
        ) {
            Column {
                Row(Modifier.padding(16.dp)) {
                    Text(
                        text = "Text",
                        style = MaterialTheme.typography.subtitle2,
                        modifier = Modifier
                            .weight(1f)
                            .align(Alignment.CenterVertically)
                    )
                }
                    ...
            }
        }

2. Run the code on a device and execute the "swipe-to-refresh" gesture
3. Error: viewmodel.refresh() is never called

## Expected behavior
viewmodel.refresh() is called

## Environment:
'com.google.accompanist:accompanist-swiperefresh:0.9.1'

## Additional context
It works fine if I use a LazyColumn with an item count of 1

### PR DESCRIPTION
**Pull request by chrisbanes**
Fixes #404

### CODE REVIEW

File: swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt [hunk 1]
```diff
@@ -182,18 +182,22 @@ private class SwipeRefreshNestedScrollConnection(
...
 
 /**
- * A layout which implements the swipe-to-refresh pattern.
+ * A layout which implements the swipe-to-refresh pattern, allowing the user to refresh content via
+ * a vertical swipe gesture.
  *
- * The layout can be used whenever the user has the ability to refresh content via a vertical
- * swipe gesture.
+ * This layout requires its content to be scrollable so that it receives vertical swipe events.
+ * The scrollable content does not need to a direct descendant though. Layouts such as
```
Comment (ricknout) [inline swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt:189]: typo: does not need to "have" a

Comment (chrisbanes) [reply swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt]: Woops, fixed.

**Review by ricknout — APPROVED** [review]
