### PR TITLE
[Web] Fix webview blocking js reload

### LINKED ISSUE #1335: [WebView] window.location.reload() broken by shouldOverrideUrlLoading
AccompanistWebViewClient overrides `shouldOverrideUrlLoading` with 

```
 override fun shouldOverrideUrlLoading(
        view: WebView?,
        request: WebResourceRequest?
    ): Boolean {
        // Override all url loads to make the single source of truth
        // of the URL the state holder Url
        request?.let {
            state.content = state.content.withUrl(it.url.toString())
        }
        return true
    }
```
Returning `true` ensures that the load is always cancelled here though since it's setting `state.content` it will normally result in the URL being loaded. However 

```
                if (url.isNotEmpty() && url != view.url) {
                    view.loadUrl(url, content.additionalHttpHeaders.toMutableMap())
                }
```
in com.google.accompanist.web.WebView explicitly skips the load if the URL has not changed. This means that javascript like `window.location.reload()` will not reload the page.

## To Reproduce
I've attached [AccompanistTest.zip](https://github.com/google/accompanist/files/9576647/AccompanistTest.zip) with a sample project demonstrating the issue.

This loads a local HTML page with a single button that should reload the page with `window.location.reload()`. On page load, `********PAGE LOADED********` should be written to console and is logged to logcat. 

This only shows up on initial page load though, the button doesn't do anything.  

Uncommenting the inelegant lines 50-52 in the sample project's MainActivity fixes the issue by avoiding the AccompanistWebViewClient.shouldOverrideUrlLoading call if the URL matches the existing URL:
```
                                if (view?.url == request?.url.toString()) {
                                    return false
                                }
```

## Expected behavior
Page should reload on `window.location.reload()` and other similar calls that normally cause pages to reload.

## Environment:
 - Android OS version: Android 13
 - Device: P6Pro
 - Accompanist version: 0.25.1

### PR DESCRIPTION
**Pull request by bentrengrove**
Fixes #1335

### CODE REVIEW

File: web/src/main/java/com/google/accompanist/web/WebView.kt [hunk 1]
```diff
@@ -204,6 +204,12 @@ open class AccompanistWebViewClient : WebViewClient() {
         view: WebView?,
         request: WebResourceRequest?
     ): Boolean {
+        // If the url hasn't changed, this is probably an internal event like
+        // a javascript reload. We should let it happen.
+        if (view?.url == request?.url.toString()) {
```
Comment (alexvanyo) [inline web/src/main/java/com/google/accompanist/web/WebView.kt:209]: If I'm understanding it correctly, this solution is to allow internal `WebView` reload requests to pass through without overriding loading.

I'm wondering if there's an alternative solution using some sort of unique ID to compare against instead of `url != view.url` to call `view.loadUrl`.

Then, instead of returning `false` here, we'd update the unique ID representing the particular request which would trigger a reload.

That might keep the number of codepaths down, and be closer to a more single-source-of-truth?
Not sure if that would change how we would want to do normal reloading.

Comment (bentrengrove) [reply web/src/main/java/com/google/accompanist/web/WebView.kt:209]: Not that I could find, you get barely any information about the request. I couldn't even tell it was from a js event in this callback.

Comment (alexvanyo) [reply web/src/main/java/com/google/accompanist/web/WebView.kt:209]: I was thinking about something like

```kotlin
    request?.let {
        state.content = state.content.withUrl(it.url.toString())
        state.requestId = UUID.randomUUID()
    }
```

And then that `requestId` could act like a `key()` to trigger a reload.

**Review by alexvanyo — APPROVED** [review]
